### ISSUE TITLE
BCL Auth Key requirement every time the App is re-run

### ISSUE THREAD

**Issue by eomere** [NREL/OpenStudioApplication#66] opened 2019-12-18 21:37 UTC
Enhancement Request
--------------

The OpenStudio App Versions for Mac and Linux should store the BCL Auth Key. The Windows Version has this functionality. 

## Detailed Description
 
After closing the App and re-running it, the BCL Auth Key has to be re-entered before one can apply measures. Also, because the Key is not stored, previously downloaded components/measures are not stored. Hence, it is mandatory to re-enter the Key, and re-download measures, before they can be applied. 

## Possible Implementation

This functionality already exists for the version of the App running on Windows, and can be replicated for Mac and Linux.

**Comment by jmarrec** [comment] 2020-03-16 20:44
@eomere closing until someone provides enough info to reproduce.

**Comment by eomere** [comment] 2020-03-18 21:21
I'm not sure that I understand how you have addressed this bug. Did you enter the Key to see if the App can read it? That is not the issue. 

Within the Windows version, I have only ever entered my BCL Key once. This info is stored. However, within the Mac and Linux versions, I have to enter my BCL Key everytime I launch the App. 

In order to reproduce this issue, you have to close the (Mac or Linux) App after entering your BCL Key and applying a Measure. When you relaunch the App, try to apply another Measure. If you need to re-enter your BCL Key, then then the App isn't working like the windows Version.

**Comment by jmarrec** [comment] 2020-03-23 13:03
Apparently my message above was confusing due to the use of SQL statements probably.

Here's what I just did, again:

1. Move BCL directory (so OSApp cannot find it)
2. Open OpenStudioApp, go to "Find Measures"
3. Prompts to add BCL Key, do that
4. Download any measure
5. Close OS APP
6. Reopen OS App
7. Go to "Find Measures"
8. <NO PROMPT FOR AUTH KEY>
9. Download another measure, to see if that works, and it does

That's what I meant by "I can't reproduce right now", and I can't fix what I can't reproduce.

@eomere A possibility might be that the SQL statements that OSApp does onto your `BCL/components.sql` aren't even commited. Can you check if you can find a `.sql-journal` file in that folder or something please?

**Comment by jmarrec** [comment] 2020-03-23 13:24
https://github.com/NREL/OpenStudio/blob/d05bc3a9ba090cf986cde56b7616b7dc445ac2f1/src/utilities/bcl/LocalBCL.cpp#L1506-L1528

I don't see a problem there at first glance.

If the RemoteBCL validates the key (the key passed is valid), then you do a transaction, and either rollback or commit it.

**Comment by eomere** [comment] 2020-03-23 15:53
Hmmm, interesting. Yes, I see now that you cannot reproduce this issue. Thanks for clarifying Julien.

**Comment by jmarrec** [comment] 2020-03-23 16:33
If you find a -journal file or something please let me know. I'll keep this one open for now, as if it can be reproduced on other machines it'd be severe bug

**Comment by eomere** [comment] 2020-03-23 16:41
What is a "-journal file"?

**Comment by jmarrec** [comment] 2020-03-23 17:28
`BCL/components.sql-journal` or similar

**Comment by eomere** [comment] 2020-03-23 20:46
Here is a [journal](https://www.dropbox.com/s/aso20wmfdzl9mo4/components.sql?dl=0) that I just pulled from Ubuntu. Will it suffice?

**Comment by jmarrec** [comment] 2020-03-25 08:32
That's your actual `components.sql` database I think. Was there a `components.sql-journal` next to it?

**Comment by jmarrec** [comment] 2020-03-25 08:41
The `components.sql` file you shared does have the BCL `prodAuthKey` stored...

```
$ sqlite3 components.sql
SQLite version 3.22.0 2018-01-22 18:45:57
Enter ".help" for usage hints.
sqlite> SELECT data FROM Settings WHERE name='prodAuthKey';
13c925......b90
```

The key appears to be 32 char long like it should, and I can use it in RemoteBCL::setProdAuthKey which returns true.

**Comment by eomere** [comment] 2020-03-25 15:01
I just tried recreating this bug in Ubuntu, but couldn't. I didn't need to re-enter my BCL Key. 

However, I downloaded a few measures. Upon closing the App, re-launching it, and accessing the Apply Measures dialog, I noticed that all downloaded Measures were not stored. I had to re-download all measures. This is not the case within Windows. Are you able to replicate this?  

Here is a copy of the [journal file](https://www.dropbox.com/s/ct0ip36w4lmevgi/components.sql-journal?dl=0)

**Comment by jmarrec** [comment] 2020-03-30 09:04
@eomere Ok so you do have a DB-journal file... That's not good, I'm bumping this to a blocker bug.

Typically we do this:
* BEGIN TRANSACTION
* <do stuff>
* Then:
    * If worked: COMMIT transaction, which actually writes to the `components.sql` file and delete the DB-journal (`components.sql-journal` file)
    * If not, ROLLBACK transaction.

The fact that the measures aren't "registered" (closing an reopening you don't have them available anymore) and that you have a sql-journal file means transactions aren't being completed, and needs to be investigated and fixed.

**Comment by jmarrec** [comment] 2020-03-30 14:21
I have reproduced this issue on my Ubuntu 18.04 machine and addresed on OpenStudio's side: NREL/OpenStudio#3934

**Comment by eomere** [comment] 2020-03-30 14:23
Sounds good. Were you able to reproduce it on your Mac?

**Closed** 2020-03-31 00:57 UTC
Labels: severity - Blocker :no_entry_sign:
